### ISSUE TITLE
placement option ignored when resclaing images

### ISSUE THREAD

**Issue by JPUnD** [themefisher/academia-hugo#24]
From the [Wowchemy Docs](https://wowchemy.com/docs/content/page-features/#featured-image) the featured image field on a post should have the following options:
```
# Featured image
# To use, place an image named `featured.jpg/png` in your page's folder.
# Placement options: 1 = Full column width, 2 = Out-set, 3 = Screen-width
# Focal point options: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
# Set `preview_only` to `true` to just use the image for thumbnails.
image:
  placement: 1
  caption: "Photo by [Geo](https://github.com/gcushen/)"
  focal_point: "Center"
  preview_only: false
  alt_text: An optional description of the image for screen readers.
```

All options work as expected in my post except for the placement option which makes no change.

**Comment by JPUnD** [comment]
For reference here's a few screenshots of my webpage, with an image that is 16:9 in 1080p

Here's the default looking post:
![image](https://user-images.githubusercontent.com/41581666/107876345-55a9d580-6ebd-11eb-8d1e-abf11f5fef5d.png)

With the following `index.md`:
```
---
title: Display Jupyter Notebooks with academia
subtitle: Learn how to blog in academia using Jupyter notebooks
summary: Learn how to blog in academia using Jupyter notebooks
authors:
- admin
tags:
- human
categories: []
date: "2019-02-05T00:00:00Z"
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal point options: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
image:
  placement: 1
  caption: 'Image credit: [**Unsplash**](https://unsplash.com/photos/CpkOjOcXdUY)'
  focal_point: "Center"
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []

# Set captions for image gallery.
gallery_item:
- album: gallery
  caption: Default
  image: theme-default.png
- album: gallery
  caption: Ocean
  image: theme-ocean.png
- album: gallery
  caption: Forest
  image: theme-forest.png
- album: gallery
  caption: Dark
  image: theme-dark.png
- album: gallery
  caption: Apogee
  image: theme-apogee.png
- album: gallery
  caption: 1950s
  image: theme-1950s.png
- album: gallery
  caption: Coffee theme with Playfair font
  image: theme-coffee-playfair.png
- album: gallery
  caption: Strawberry
  image: theme-strawberry.png
---
```

As you can see the `placement` option provides no change.

Here's how it looks with the image being just a preview:
![image](https://user-images.githubusercontent.com/41581666/107876390-a91c2380-6ebd-11eb-9359-fad25d390267.png)

This is exactly how i wanted it to work, but with an image on top that would fill the column width, regardless if it had to upscale or how look very big, I would then take care of the resolution myself.

It also makes the author, date, time to read and social media share much better.

In a cellphone it also looks good as it fits everything to width:
![image](https://user-images.githubusercontent.com/41581666/107876466-0fa14180-6ebe-11eb-8237-e44199e4fe47.png)
